# This template uses jdk21 for verifying and deploying images
image: gradle:jdk21

# Define possible stages
stages:
  - build
  - publish
  - deploy

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  key: $CI_COMMIT_BRANCH
  paths:
    - .gradle
    - build

# Build
assemble:
  stage: build
  script:
    - './gradlew clean assemble'
  except:
    - master

# Publish to MassiveCraft Maven
publish:
  stage: publish
  except:
    - tags
  before_script:
    - 'git config --global user.email "root@massivecraft.team"'
    - 'git config --global user.name "MassiveCraft"'
  script:
    - './gradlew publish'

# Deploy to Test Server
deploy:jdk21:
  stage: deploy
  script:
    - 'echo "Dummy task to deploy to Test"'
  when: manual
